Development
large-scale-gxe-methods/GEM pull request #27
Opened 2024-05-21 18:27 UTC by samanehsalehi

Updated broken link and README.md

2024-05-21 20:30 UTC, hanchenphd requested changes
It looks like all (over 100) files under thirdparty/ were labeled as changed, but I could not see any changes. In that case, it would be nice to keep the old version, so that this pull request does not show 121 files were changed.

2024-05-21 20:30 UTC, hanchenphd commented on README.md
> +* Included stratified values for binary outcomes
"Included stratified N and AF for binary outcomes"

2024-05-21 20:30 UTC, hanchenphd commented on example/my_example.out
Can you investigate why N_Samples had changed from 250 to 500?

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/COPYING
I could not see what has been changed here... The old and new versions look identical.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/NEWS.md
Same here. The old and new versions look identical. In that case, it would be nice to keep the old version unchanged.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/README.md
Same here. The old and new versions look identical. In that case, it would be nice to keep the old version unchanged.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/common/common_defs.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/common_defs.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/adler32.c
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/adler32_vec_template.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/adler32_impl.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/cpu_features.c
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/cpu_features.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/crc32_impl.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/crc32_pmull_helpers.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/crc32_pmull_wide.h
See above.

2024-05-21 20:30 UTC, hanchenphd commented on thirdparty/libdeflate-1.18/lib/arm/matchfinder_impl.h
See above.

2024-05-26 04:57 UTC, hanchenphd commented on LICENSE
Does this file have the eol issue?

2024-05-26 04:58 UTC, hanchenphd commented on README.md
Does this file have the eol issue?

2024-05-26 04:58 UTC, hanchenphd commented on example/my_example.out
Does this file have the eol issue?

2024-05-26 04:58 UTC, hanchenphd commented on src/GEM.cpp
Does this file have the eol issue?

2024-05-26 04:59 UTC, hanchenphd commented on src/ReadParameters.cpp
Does this file have the eol issue?

2024-05-26 04:59 UTC, hanchenphd commented on src/makefile
Does this file have the eol issue?

2024-05-26 05:00 UTC, hanchenphd requested changes
Please check these files with large diff between commits and see if any of them had the eol issue.

2024-05-26 11:32 UTC, samanehsalehi commented
Hi Han,
I will check that and will update you.


Sent from Yahoo Mail for iPhone


On Sunday, May 26, 2024, 12:01 AM, Han Chen ***@***.***> wrote:




@hanchenphd requested changes on this pull request.

Please check these files with large diff between commits and see if any of them had the eol issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-29 16:23 UTC, samanehsalehi commented on LICENSE
I use git diff to compare "4f09280fd6b54521a0e05760fe9252501d4052d2" , which happened before merge pull request 25,  with the latest commit. Files in thirdparty folder mostly have EOL =LF. While .c and .h file in "src" folder have EOL = CRLF, also my_example.out has EOL =LF.  The latest commit EOL now is the same as "4f09280fd6b54521a0e05760fe9252501d4052d2".

2024-05-30 13:30 UTC, hanchenphd approved these changes

2024-05-30 13:31 UTC, merged